# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm ci
      working-directory: ./test3-env
    - run: npm run build --if-present
      working-directory: ./test3-env
    - run: npm test
      working-directory: ./test3-env
    
    - name: Official SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v2.0.1
      with:
         # Additional arguments to the sonar-scanner
         args: >
           -Dsonar.projectKey=dev_test_github
           -Dsonar.projectName=dev_test_github
           -Dsonar.exclusions=**/bin/**,**.json,**/obj/*,**.xml,**/testresult/**
         projectBaseDir: ./test3-env
      env:
         #BRANCH: ${{github.event.pull_request.head.ref}}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}    
